# Esquemas básicos requeridos
include /etc/ldap/schema/core.schema
include /etc/ldap/schema/cosine.schema
include /etc/ldap/schema/nis.schema
include /etc/ldap/schema/inetorgperson.schema

# Ruta donde Ubuntu guarda los módulos de OpenLDAP
modulepath /usr/lib/ldap
moduleload back_mdb.la

# Configuración de base de datos de la Réplica
database mdb
suffix "dc=fis,dc=epn,dc=ec"
rootdn "cn=admin,dc=fis,dc=epn,dc=ec"
rootpw admin
directory /var/lib/ldap2

# Sincronización nativa (Syncrepl) apuntando al puerto 389
syncrepl rid=001
  provider=ldap://127.0.0.1:389
  type=refreshAndPersist
  interval=00:00:00:10
  searchbase="dc=fis,dc=epn,dc=ec"
  bindmethod=simple
  binddn="cn=admin,dc=fis,dc=epn,dc=ec"
  credentials=password
